TICK_INTERVAL = 1.0
SNAPSHOT_BROADCAST_INTERVAL = 2
RESERVATION_TIMEOUT = 10
MAX_CORRIDOR_LENGTH = 3
DEADLOCK_CHECK_INTERVAL = 5
CONFLICT_RULE = "priority_hysteresis"
PEAK_MULTIPLIER = 1.2

ALPHA = 0.7
BETA = 0.3
WAIT_ALPHA = 0.01
PRIORITY_HYSTERESIS_MARGIN = 0.05
MIN_RESERVATION_HOLD_TICKS = 2
MAX_RETRY_BEFORE_REPLAN = 3
REVOCATION_COOLDOWN_TICKS = 3
DEFAULT_PHASE_DURATION = 30
